variables:
  APP_NAME: "th2-csv-codec"
  MAJOR_VERSION: "1"
  MINOR_VERSION: "3"
  MAINTENANCE_VERSION: '0'
  DOCKER_PUBLISH_ENABLED: 'false'
  INSPECTION_ENABLED: 'true'

include:
  - project: 'vivarium/th2/pipelines'
    ref: master
    file: '/.gitlab-ci-java.yml'
